name: Push components to Espressif Component Registry

on:
  push:
    branches:
      - master

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Upload components to component registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: |
            rmaker_common: .
            components/rmaker_work_queue
            components/rmaker_cmd_resp
            components/rmaker_console
            components/rmaker_common_events
            components/rmaker_system_ctrl
            components/rmaker_time_sync
          namespace: "espressif"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
